const STYLUS_EOF_MAGIC: u8 = 0xEF;
const STYLUS_EOF_MAGIC_SUFFIX: u8 = 0xF0;
const STYLUS_EOF_VERSION: u8 = 0x00;

pub const STYLUS_DISCRIMINANT: &[u8] = &[
    STYLUS_EOF_MAGIC,
    STYLUS_EOF_MAGIC_SUFFIX,
    STYLUS_EOF_VERSION,
];
